# Docker Compose para E-commerce Monorepo
version: '3.8'

services:
  # Banco de dados PostgreSQL
  api:
    build: ./apps/api
    env_file:
      - ./apps/api/.env
    depends_on:
      - postgres
    networks:
      - ecommerce-network

  postgres:
    image: postgres:15-alpine
    container_name: ecommerce-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db:/docker-entrypoint-initdb.d
    networks:
      - ecommerce-network

  # Cache Redis (opcional)
  redis:
    image: redis:7-alpine
    container_name: ecommerce-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ecommerce-network

  # Adminer - Interface web para banco (desenvolvimento)
  adminer:
    image: adminer:latest
    container_name: ecommerce-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - ecommerce-network

# Volumes para persistir dados
volumes:
  postgres_data:
  redis_data:

# Rede para comunicação entre containers
networks:
  ecommerce-network:
    driver: bridge
